apiVersion: v1
kind: Namespace
metadata:
  name: jenkins
  
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins
  namespace: jenkins
  labels:
    app: jenkins
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      serviceAccountName: jenkins-admin
      containers:
        - name: jenkins
          image: ahmedemad2025/jenkins-kubectl-docker:v3
          ports:
            - containerPort: 8080
          volumeMounts:
          - name: jenkins-vol
            mountPath: /var/jenkins_home
          - name: docker
            mountPath: /var/run
      volumes:
        - name: jenkins-vol
          emptyDir: {}
        - name: docker
          hostPath:
            path: /var/run        
---
apiVersion: v1
kind: Service
metadata:
  name: loadbalancer
  namespace: jenkins
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: 'true'
spec:
  selector:
    app: jenkins
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
